'use client';
import { useMemo, useState } from 'react';
type Option = { id: number; name: string };
export type GenerationConfigValue = { departmentId:number|null; sectionId:number|null; courseIds:number[]; teacherIds:number[]; roomIds:number[]; timeSlotIds:number[] };
export default function GenerationConfig({departments,sections,courses,teachers,rooms,timeSlots,onGenerate}:{departments:Option[];sections:Option[];courses:Option[];teachers:Option[];rooms:Option[];timeSlots:Option[];onGenerate:(config:GenerationConfigValue)=>void}){
 const [departmentId,setDepartmentId]=useState<number|null>(null),[sectionId,setSectionId]=useState<number|null>(null),[courseIds,setCourseIds]=useState<number[]>([]),[teacherIds,setTeacherIds]=useState<number[]>([]),[roomIds,setRoomIds]=useState<number[]>([]),[timeSlotIds,setTimeSlotIds]=useState<number[]>([]);
 const toggle=(setter:React.Dispatch<React.SetStateAction<number[]>>,id:number)=>setter(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const can=useMemo(()=>!!departmentId&&!!sectionId&&courseIds.length>0&&teacherIds.length>0&&roomIds.length>0&&timeSlotIds.length>0,[departmentId,sectionId,courseIds,teacherIds,roomIds,timeSlotIds]);
 return <section className="mb-5 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="mb-5"><p className="text-xs font-semibold uppercase tracking-wider text-cyan-400">Generation configuration</p><h2 className="mt-1 text-lg font-semibold">Choose scheduling resources</h2><p className="mt-1 text-sm text-slate-500">Only selected resources are considered by the generator.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
 <Select label="Department" value={departmentId} setValue={setDepartmentId} options={departments}/><Select label="Section" value={sectionId} setValue={setSectionId} options={sections}/><Multi label="Courses" options={courses} selected={courseIds} toggle={id=>toggle(setCourseIds,id)}/><Multi label="Teachers" options={teachers} selected={teacherIds} toggle={id=>toggle(setTeacherIds,id)}/><Multi label="Rooms" options={rooms} selected={roomIds} toggle={id=>toggle(setRoomIds,id)}/><Multi label="Time Slots" options={timeSlots} selected={timeSlotIds} toggle={id=>toggle(setTimeSlotIds,id)}/></div><button disabled={!can} onClick={()=>onGenerate({departmentId,sectionId,courseIds,teacherIds,roomIds,timeSlotIds})} className="mt-5 rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40">Generate selected resources</button></section>;
}
function Select({label,value,setValue,options}:{label:string;value:number|null;setValue:(v:number|null)=>void;options:Option[]}){return <label className="text-xs text-slate-500">{label}<select value={value??''} onChange={e=>setValue(e.target.value?Number(e.target.value):null)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"><option value="">Select {label.toLowerCase()}</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
function Multi({label,options,selected,toggle}:{label:string;options:Option[];selected:number[];toggle:(id:number)=>void}){return <fieldset><legend className="text-xs text-slate-500">{label}</legend><div className="mt-1 max-h-28 overflow-auto rounded-lg border border-slate-700 bg-slate-950 p-2">{options.map(x=><label key={x.id} className="flex items-center gap-2 rounded px-2 py-1.5 text-xs text-slate-300 hover:bg-slate-900"><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/>{x.name}</label>)}</div></fieldset>}
